#!/usr/bin/env python3
"""Scaffold self-contained HTML artifacts for the visualization skill."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from html import escape
from pathlib import Path


THEMES = {
    "blueprint": {
        "bg": "#0d1b2a",
        "panel": "#132238",
        "text": "#e8f1ff",
        "muted": "#9ab0cc",
        "accent": "#67b7ff",
        "border": "rgba(103, 183, 255, 0.25)",
    },
    "editorial": {
        "bg": "#f4efe8",
        "panel": "#fffaf4",
        "text": "#201a17",
        "muted": "#6c625c",
        "accent": "#9a5b3f",
        "border": "rgba(154, 91, 63, 0.18)",
    },
    "paper-ink": {
        "bg": "#faf7f2",
        "panel": "#fffdf8",
        "text": "#2d2824",
        "muted": "#6f665f",
        "accent": "#7f8c5a",
        "border": "rgba(92, 104, 58, 0.18)",
    },
    "terminal": {
        "bg": "#08110a",
        "panel": "#0e1a11",
        "text": "#b7f7bf",
        "muted": "#82b889",
        "accent": "#4de06f",
        "border": "rgba(77, 224, 111, 0.2)",
    },
    "product": {
        "bg": "#f5f7fb",
        "panel": "#ffffff",
        "text": "#111827",
        "muted": "#667085",
        "accent": "#0f62fe",
        "border": "rgba(15, 98, 254, 0.14)",
    },
    "data-desk": {
        "bg": "#fbfbfd",
        "panel": "#ffffff",
        "text": "#14161c",
        "muted": "#5b6270",
        "accent": "#005c53",
        "border": "rgba(0, 92, 83, 0.16)",
    },
}


DEFAULT_SECTIONS = {
    "explainer": [
        ("Overview", "Summarize the system, topic, or decision in plain language."),
        ("Key Components", "List the parts, responsibilities, or moving pieces."),
        ("Risks / Caveats", "Capture the important tradeoffs, unknowns, and failure modes."),
        ("Next Steps", "Recommend the concrete next actions for the reader."),
    ],
    "review": [
        ("What Looks Strong", "Call out the parts that are well-supported or correctly aligned."),
        ("Gaps and Risks", "List the mismatches, regressions, or unclear areas."),
        ("Recommendation", "State the decision or follow-up path clearly."),
    ],
    "slides": [
        ("Context", "Explain what this artifact is about and why it matters."),
        ("Core Insight", "Show the single most important takeaway."),
        ("Decision / Ask", "End with the recommendation, action, or next move."),
    ],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scaffold a visualization HTML artifact.")
    parser.add_argument("--mode", choices=["explainer", "review", "slides"], default="explainer")
    parser.add_argument(
        "--theme",
        choices=sorted(THEMES.keys()),
        default="blueprint",
        help="Visual direction for the scaffolded page.",
    )
    parser.add_argument("--title", required=True, help="Primary title for the page.")
    parser.add_argument("--subtitle", default="", help="Subtitle or framing sentence.")
    parser.add_argument("--output", required=True, help="Output HTML path.")
    parser.add_argument(
        "--section",
        action="append",
        default=[],
        help="Repeatable section in the form 'Heading|Body'.",
    )
    parser.add_argument(
        "--card",
        action="append",
        default=[],
        help="Repeatable summary card in the form 'Label|Value|Body'.",
    )
    return parser.parse_args()


def load_template(mode: str) -> str:
    base = Path(__file__).resolve().parent.parent / "templates"
    filename = {
        "explainer": "explainer.html",
        "review": "review.html",
        "slides": "slide-mode.html",
    }[mode]
    return (base / filename).read_text(encoding="utf-8")


def parse_parts(raw: str, expected_parts: int) -> list[str]:
    parts = [part.strip() for part in raw.split("|", expected_parts - 1)]
    if len(parts) != expected_parts or any(not part for part in parts):
        raise ValueError(f"Invalid value: {raw!r}")
    return parts


def build_sections(mode: str, section_args: list[str]) -> str:
    sections = []
    raw_sections = section_args or [f"{title}|{body}" for title, body in DEFAULT_SECTIONS[mode]]
    for raw in raw_sections:
        title, body = parse_parts(raw, 2)
        sections.append(
            "<section class=\"section\">"
            f"<h2>{escape(title)}</h2>"
            f"<p>{escape(body)}</p>"
            "</section>"
        )
    return "\n".join(sections)


def build_cards(card_args: list[str]) -> str:
    if not card_args:
        card_args = [
            "Mode|Scaffolded|Starter artifact generated by visualization.",
            "Audience|Mixed|Tune the density and language before delivery.",
            "Next move|Refine|Replace placeholders with real content.",
        ]

    cards = []
    for raw in card_args:
        label, value, body = parse_parts(raw, 3)
        cards.append(
            "<article class=\"card\">"
            f"<strong>{escape(label)}</strong>"
            f"<div>{escape(value)}</div>"
            f"<p>{escape(body)}</p>"
            "</article>"
        )
    return "\n".join(cards)


def build_matrix() -> str:
    rows = [
        ("Scope", "Aligned", "What is explicitly covered."),
        ("Risks", "Needs attention", "What could fail or stay ambiguous."),
        ("Recommendation", "Action required", "What should happen next."),
    ]
    cells = []
    for area, status, notes in rows:
        css_class = {
            "Aligned": "status-good",
            "Needs attention": "status-warn",
            "Action required": "status-bad",
        }[status]
        cells.append(
            "<tr>"
            f"<td>{escape(area)}</td>"
            f"<td class=\"{css_class}\">{escape(status)}</td>"
            f"<td>{escape(notes)}</td>"
            "</tr>"
        )
    return (
        "<table class=\"matrix\">"
        "<thead><tr><th>Area</th><th>Status</th><th>Notes</th></tr></thead>"
        f"<tbody>{''.join(cells)}</tbody>"
        "</table>"
    )


def build_slides(args: argparse.Namespace) -> str:
    slides = []
    raw_sections = args.section or [f"{title}|{body}" for title, body in DEFAULT_SECTIONS["slides"]]

    slides.append(
        "<section class=\"slide\">"
        "<div class=\"kicker\">Visualization / Slide Mode</div>"
        f"<h1>{escape(args.title)}</h1>"
        f"<div class=\"lede\">{escape(args.subtitle or 'Presentation-ready starter deck generated by visualization.')}</div>"
        "</section>"
    )

    for raw in raw_sections:
        heading, body = parse_parts(raw, 2)
        bullets = "".join(
            f"<li>{escape(part.strip())}</li>"
            for part in body.split(";")
            if part.strip()
        )
        slides.append(
            "<section class=\"slide\">"
            "<div class=\"kicker\">Key Section</div>"
            f"<h2>{escape(heading)}</h2>"
            f"<div class=\"body\">{escape(body)}</div>"
            f"<ul class=\"bullets\">{bullets}</ul>"
            "</section>"
        )
    return "\n".join(slides)


def render_html(args: argparse.Namespace) -> str:
    template = load_template(args.mode)
    theme = THEMES[args.theme]
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    replacements = {
        "__TITLE__": escape(args.title),
        "__SUBTITLE__": escape(args.subtitle or "Generated with the visualization scaffold."),
        "__TIMESTAMP__": escape(timestamp),
        "__BG__": theme["bg"],
        "__PANEL__": theme["panel"],
        "__TEXT__": theme["text"],
        "__MUTED__": theme["muted"],
        "__ACCENT__": theme["accent"],
        "__BORDER__": theme["border"],
        "__SUMMARY_CARDS__": build_cards(args.card),
    }

    if args.mode == "slides":
        replacements["__SLIDES__"] = build_slides(args)
    else:
        replacements["__SECTIONS__"] = build_sections(args.mode, args.section)
        if args.mode == "review":
            replacements["__MATRIX__"] = build_matrix()

    html = template
    for needle, value in replacements.items():
        html = html.replace(needle, value)
    return html


if __name__ == "__main__":
    arguments = parse_args()
    output_path = Path(arguments.output).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_html(arguments), encoding="utf-8")
    print(output_path)
